#!/bin/bash

# Run rustfmt on all modified files.
# Based on: https://stackoverflow.com/a/71222423

edition=$(echo "$(cat Cargo.toml)" | grep -oP '^(?!#)\s*edition\s*=\s*"\K.*(?=")' | head -n 1)

if [[ -z "$edition" ]]; then
  edition=2015
fi

exe=$(which rustfmt)

if [ -n "$exe" ]
then
    # field separator to the new line
    IFS=$'\n'

    for line in $(git status -s)
    do
        # if added or modified
        if [[ $line == A* || $line == M* ]]
        then
            # check file extension
            if [[ $line == *.rs ]]
            then
                # format file
                rustfmt $(pwd)/${line:3} --edition $edition
                # add changes
                git add $(pwd)/${line:3}
            fi
        fi
    done

else
    echo "rustfmt was not found."
fi
